/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.User;
import Backend.Peminjaman;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Ichsan
 */
public class Datauser extends javax.swing.JFrame {

    /**
     * Creates new form Databuku
     */
    public Datauser() {
        initComponents();
        User us = new User();
        us.r = us.getUser();
        loaddata(us);
        usernameField.setEnabled(false);
        passwordField.setEnabled(false);
        levelComboBox.setEnabled(false);
        emailField.setEnabled(false);
        editButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        levelComboBox = new javax.swing.JComboBox<>();
        levelLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        emailField = new javax.swing.JTextField();
        usernamelamaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bukuTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        titleLabel.setText("MANAJEMEN PERPUSTAKAAN");

        sectionLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        sectionLabel.setText("DATA USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sectionLabel)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectionLabel))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        usernameLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        usernameLabel.setText("Username");

        passwordLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        passwordLabel.setText("Password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        emailLabel.setText("Email");

        levelComboBox.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        levelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelComboBoxActionPerformed(evt);
            }
        });

        levelLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        levelLabel.setText("Level");

        saveButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        usernamelamaLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(levelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameField)
                    .addComponent(passwordField)
                    .addComponent(levelComboBox, 0, 241, Short.MAX_VALUE)
                    .addComponent(emailField))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(searchButton))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editButton)
                    .addComponent(refreshButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(usernamelamaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton)
                    .addComponent(editButton)
                    .addComponent(usernameLabel))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusButton)
                    .addComponent(refreshButton)
                    .addComponent(passwordLabel))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(searchButton)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelLabel)
                            .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernamelamaLabel)
                        .addGap(15, 15, 15))))
        );

        bukuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Email", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bukuTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loaddata(User us){
        String Jabatan = "";
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Username");
        t.addColumn("Password");
        t.addColumn("Email");
        t.addColumn("Level");
        bukuTable.setModel(t);
        
        try {
            while (us.r.next()) {
                try {
                    if("1".equals(us.r.getString("level"))){
                       Jabatan = "User"; 
                    }
                    else{
                       Jabatan = "Admin";
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Datauser.class.getName()).log(Level.SEVERE, null, ex);
                }
                t.addRow(new Object[] {
                    us.r.getString("username"),
                    us.r.getString("pass"),
                    us.r.getString("email"),
                    Jabatan
                });
            }
            us.r.close();
        } catch (Exception e) {
             javax.swing.JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private boolean hasPeminjaman(String username) throws SQLException {
        Peminjaman pem = new Peminjaman();
        pem.setUsername(username);
        pem.r = pem.getPeminjamanUsername();
        if(pem.r.next()){
            return true;
        }
        else{
            return false;
        }
    }
    
    private void levelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelComboBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        usernameField.setEnabled(true);
        passwordField.setEnabled(true);
        levelComboBox.setEnabled(true);
        emailField.setEnabled(true);
        editButton.setEnabled(false);
        hapusButton.setEnabled(false);
        searchButton.setEnabled(false);
        if (usernameField.getText().isEmpty() || passwordField.getText().isEmpty() || emailField.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Isi semua kolom yang diperlukan");
            return;
        }
        else{
            User us = new User();
            us.setUsernamebaru(usernameField.getText());
            us.r = us.getUserUsername();
            try {
                if (us.r.next()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Terdapat Duplikat Data (username)");
                    usernameField.setText(null);
                    usernameField.requestFocus();
                    return;
                } 
            } catch (SQLException ex) {
                Logger.getLogger(Datauser.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            us.setUsernamebaru(usernameField.getText());
            us.setPass(passwordField.getText());
            us.setEmail(emailField.getText());
            us.setLevel((String) levelComboBox.getSelectedItem());
            
            us.insertUser();
            us.r = us.getUser();
            loaddata(us);
            
            javax.swing.JOptionPane.showMessageDialog(null, "Save Success");
        }
        usernameField.setText(null);
        passwordField.setText(null);
        levelComboBox.setSelectedIndex(0);
        emailField.setText(null);
        usernameField.setEnabled(false);
        passwordField.setEnabled(false);
        levelComboBox.setEnabled(false);
        emailField.setEnabled(false);
        hapusButton.setEnabled(true);
        searchButton.setEnabled(true);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (usernameField.getText().isEmpty() || passwordField.getText().isEmpty() || emailField.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Isi semua kolom yang diperlukan");
            return;
        }      
        else
        {   
            User us = new User();
            us.setUsernamelama(usernamelamaLabel.getText());
            us.setUsernamebaru(usernameField.getText());
            us.setPass(passwordField.getText());
            us.setEmail(emailField.getText());
            us.setLevel((String) levelComboBox.getSelectedItem());
            
            us.updateUser();
            javax.swing.JOptionPane.showMessageDialog(null, "Edit Success");
            
            us.r =  us.getUser();
            loaddata(us);
            
            usernameField.setText(null);
            passwordField.setText(null);
            emailField.setText(null);
            usernamelamaLabel.setText(null);
            usernameField.setEnabled(false);
            passwordField.setEnabled(false);
            levelComboBox.setEnabled(false);
            emailField.setEnabled(false);
            editButton.setEnabled(false);
            saveButton.setEnabled(true);
            hapusButton.setEnabled(true);
            searchButton.setEnabled(true);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        editButton.setEnabled(false);
        saveButton.setEnabled(false);
        searchButton.setEnabled(false);
        usernameField.setEnabled(true);
        if (usernameField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
            usernameField.requestFocus();
            return;
        }  
        else
        {
            String username = usernameField.getText();
            try {
                if (hasPeminjaman(username)) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Tidak dapat menghapus user karena user sedang meminjam");
                    return;
                }
                else{
                    User us = new User();
                    us.setUsernamebaru(usernameField.getText());
                    us.r = us.getUserUsername();
                    
                    if (!us.r.next()) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Data User tidak ditemukan");
                        usernameField.setText(null);
                        usernameField.requestFocus();
                        return; 
                    }
                    
                    us.deleteUser();

                    javax.swing.JOptionPane.showMessageDialog(null, "Delete Success");
                    
                    us.r = us.getUser();
                    loaddata(us);

                    usernameField.setEnabled(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Datauser.class.getName()).log(Level.SEVERE, null, ex);
            }
        usernameField.setText(null);
        saveButton.setEnabled(true);
        searchButton.setEnabled(true);
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        usernameField.setText(null);
        passwordField.setText(null);
        levelComboBox.setSelectedIndex(0); // Mengatur combo box kembali ke indeks 0 (Pilih)
        emailField.setText(null);
        usernamelamaLabel.setText(null);
        usernameField.setEnabled(false);
        passwordField.setEnabled(false);
        levelComboBox.setEnabled(false);
        emailField.setEnabled(false);
        saveButton.setEnabled(true);
        hapusButton.setEnabled(true);
        searchButton.setEnabled(true);
        User us = new User();
        us.r =  us.getUser();
        loaddata(us);
        
        javax.swing.JOptionPane.showMessageDialog(null, "Refresh Success");
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        new Main_Menu5().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        saveButton.setEnabled(false);
        hapusButton.setEnabled(false);
        usernameField.setEnabled(true);
        if(usernameField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Isi Kolom Username");
            usernameField.requestFocus();
            return;
        }
        else{
            User us = new User();
            us.setUsernamebaru(usernameField.getText());
            try{
                us.r = us.getUserUsername();
                
                if (!us.r.next()) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Data User tidak ditemukan");
                        usernameField.setText(null);
                        usernameField.requestFocus();
                        return; 
                    }
                
                us.r = us.getUserUsername();
                while(us.r.next()){
                    usernamelamaLabel.setText(usernameField.getText());
                    passwordField.setText(us.r.getString("pass"));
                    emailField.setText(us.r.getString("email"));
                    levelComboBox.setSelectedItem(us.r.getString("level"));
                    javax.swing.JOptionPane.showMessageDialog(null, "Search Success");
                }
                us.r =  us.getUserUsername();
                loaddata(us);
                editButton.setEnabled(true);
                saveButton.setEnabled(false);
                hapusButton.setEnabled(false);
                searchButton.setEnabled(false);
                passwordField.setEnabled(true);
                levelComboBox.setEnabled(true);
                emailField.setEnabled(true);
            } catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datauser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datauser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bukuTable;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> levelComboBox;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernamelamaLabel;
    // End of variables declaration//GEN-END:variables
}
