/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Main_Menu5 extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dataBukuPanel = new javax.swing.JPanel();
        dataBukuLabel = new javax.swing.JLabel();
        datauserPanel = new javax.swing.JPanel();
        datauserLabel = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        datapeminjamanPanel = new javax.swing.JPanel();
        datapeminjamanLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        titleLabel.setText("MANAJEMEN PERPUSTAKAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(titleLabel)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dataBukuPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dataBukuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataBukuPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataBukuPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataBukuPanelMouseExited(evt);
            }
        });

        dataBukuLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        dataBukuLabel.setText("DATA BUKU");
        dataBukuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataBukuLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataBukuLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataBukuLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout dataBukuPanelLayout = new javax.swing.GroupLayout(dataBukuPanel);
        dataBukuPanel.setLayout(dataBukuPanelLayout);
        dataBukuPanelLayout.setHorizontalGroup(
            dataBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBukuPanelLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(dataBukuLabel)
                .addGap(163, 163, 163))
        );
        dataBukuPanelLayout.setVerticalGroup(
            dataBukuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBukuPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(dataBukuLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        datauserPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        datauserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datauserPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datauserPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datauserPanelMouseExited(evt);
            }
        });

        datauserLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        datauserLabel.setText("DATA USER");
        datauserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datauserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datauserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datauserLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout datauserPanelLayout = new javax.swing.GroupLayout(datauserPanel);
        datauserPanel.setLayout(datauserPanelLayout);
        datauserPanelLayout.setHorizontalGroup(
            datauserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datauserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(datauserLabel)
                .addGap(164, 164, 164))
        );
        datauserPanelLayout.setVerticalGroup(
            datauserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datauserPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(datauserLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        logoutPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelMouseExited(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        logoutLabel.setText("LOGOUT");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(logoutLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logoutLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        datapeminjamanPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        datapeminjamanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datapeminjamanPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datapeminjamanPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datapeminjamanPanelMouseExited(evt);
            }
        });

        datapeminjamanLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        datapeminjamanLabel.setText("DATA PEMINJAMAN");
        datapeminjamanLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datapeminjamanLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datapeminjamanLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datapeminjamanLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout datapeminjamanPanelLayout = new javax.swing.GroupLayout(datapeminjamanPanel);
        datapeminjamanPanel.setLayout(datapeminjamanPanelLayout);
        datapeminjamanPanelLayout.setHorizontalGroup(
            datapeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datapeminjamanPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(datapeminjamanLabel)
                .addGap(130, 130, 130))
        );
        datapeminjamanPanelLayout.setVerticalGroup(
            datapeminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datapeminjamanPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(datapeminjamanLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataBukuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datauserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datapeminjamanPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(dataBukuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(datauserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(datapeminjamanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataBukuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBukuPanelMouseClicked
        // TODO add your handling code here:
        new Databuku().setVisible(true);
        this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
    }//GEN-LAST:event_dataBukuPanelMouseClicked

    private void datauserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserPanelMouseClicked
        // TODO add your handling code here:
        new Datauser().setVisible(true);
        this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
    }//GEN-LAST:event_datauserPanelMouseClicked

    private void dataBukuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBukuLabelMouseClicked
        // TODO add your handling code here:
        new Databuku().setVisible(true);
        this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
    }//GEN-LAST:event_dataBukuLabelMouseClicked

    private void dataBukuLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBukuLabelMouseEntered
        // TODO add your handling code here:
        dataBukuLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_dataBukuLabelMouseEntered

    private void dataBukuLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBukuLabelMouseExited
        // TODO add your handling code here:
        dataBukuLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_dataBukuLabelMouseExited

    private void dataBukuPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBukuPanelMouseEntered
        // TODO add your handling code here:
        dataBukuPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_dataBukuPanelMouseEntered

    private void dataBukuPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBukuPanelMouseExited
        // TODO add your handling code here:
        dataBukuPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_dataBukuPanelMouseExited

    private void datauserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserLabelMouseClicked
        // TODO add your handling code here:
        new Datauser().setVisible(true);
        this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
    }//GEN-LAST:event_datauserLabelMouseClicked

    private void datauserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserLabelMouseEntered
        // TODO add your handling code here:
        datauserLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_datauserLabelMouseEntered

    private void datauserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserLabelMouseExited
        // TODO add your handling code here:
        datauserLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_datauserLabelMouseExited

    private void datauserPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserPanelMouseEntered
        // TODO add your handling code here:
        datauserPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_datauserPanelMouseEntered

    private void datauserPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserPanelMouseExited
        // TODO add your handling code here:
        datauserPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_datauserPanelMouseExited

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Yakin mau logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // Tindakan jika pengguna memilih "Ya"
            new Main_Menu1().setVisible(true);
            this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
        } else {
            // Tindakan jika pengguna memilih "Tidak" atau menutup dialog
            JOptionPane.showMessageDialog(null, "Logout dibatalkan.");
        }
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        // TODO add your handling code here:
        logoutLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        // TODO add your handling code here:
        logoutLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_logoutLabelMouseExited

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Yakin mau logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // Tindakan jika pengguna memilih "Ya"
            new Main_Menu1().setVisible(true);
            this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
        } else {
            // Tindakan jika pengguna memilih "Tidak" atau menutup dialog
            JOptionPane.showMessageDialog(null, "Logout dibatalkan.");
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void logoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseEntered
        // TODO add your handling code here:
        logoutPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutPanelMouseEntered

    private void logoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseExited
        // TODO add your handling code here:
        logoutPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_logoutPanelMouseExited

    private void datapeminjamanLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapeminjamanLabelMouseClicked
        // TODO add your handling code here:
        new Datapeminjaman().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datapeminjamanLabelMouseClicked

    private void datapeminjamanLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapeminjamanLabelMouseEntered
        // TODO add your handling code here:
        datapeminjamanLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_datapeminjamanLabelMouseEntered

    private void datapeminjamanLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapeminjamanLabelMouseExited
        // TODO add your handling code here:
        datapeminjamanLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_datapeminjamanLabelMouseExited

    private void datapeminjamanPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapeminjamanPanelMouseClicked
        // TODO add your handling code here:
        new Datapeminjaman().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_datapeminjamanPanelMouseClicked

    private void datapeminjamanPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapeminjamanPanelMouseEntered
        // TODO add your handling code here:
        datapeminjamanPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_datapeminjamanPanelMouseEntered

    private void datapeminjamanPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapeminjamanPanelMouseExited
        // TODO add your handling code here:
        datapeminjamanPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_datapeminjamanPanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataBukuLabel;
    private javax.swing.JPanel dataBukuPanel;
    private javax.swing.JLabel datapeminjamanLabel;
    private javax.swing.JPanel datapeminjamanPanel;
    private javax.swing.JLabel datauserLabel;
    private javax.swing.JPanel datauserPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
