/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Koneksi;
import Backend.Buku;
import Backend.Peminjaman;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import Backend.Koneksi;
import Backend.User;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author ASUS
 */
public class Pinjam extends javax.swing.JFrame {

    private static long daysBetween(Calendar startDate, Calendar endDate) {
        long millisecondsPerDay = 24 * 60 * 60 * 1000;
        long startMillis = startDate.getTimeInMillis();
        long endMillis = endDate.getTimeInMillis();
        return (endMillis - startMillis) / millisecondsPerDay;
    }
    
    // Method untuk mengatur nilai loggedInUsername dari kelas Loginmhs
    
    private void loaddata() {
        Buku buk = new Buku();
        int i = 0;
        try{
            buk.r = buk.getBuku();
            while(buk.r.next()){
                bukuTable.setValueAt(buk.r.getString("id_buku"), i, 0) ;
                bukuTable.setValueAt(buk.r.getString("judul"), i, 1) ;
                bukuTable.setValueAt(buk.r.getString("jenis") , i, 2);
                bukuTable.setValueAt(buk.r.getString("tahun_terbit"), i, 3);
                i++;
            }
            buk.r.close();
        } catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }

    /**
     * Creates new form Pinjam
     */
    public Pinjam() {
        initComponents();
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        idtransaksiLabel = new javax.swing.JLabel();
        idtransaksiField = new javax.swing.JTextField();
        idbukuLabel = new javax.swing.JLabel();
        idbukuField = new javax.swing.JTextField();
        tglpinjamLabel = new javax.swing.JLabel();
        tglpinjamDate = new com.toedter.calendar.JDateChooser();
        tglkembaliLabel = new javax.swing.JLabel();
        tglkembaliDate = new com.toedter.calendar.JDateChooser();
        pinjamButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bukuTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 204));

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        titleLabel.setText("Peminjaman Buku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(titleLabel))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        usernameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        usernameLabel.setText("Username");

        idtransaksiLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        idtransaksiLabel.setText("ID Transaksi");

        idbukuLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        idbukuLabel.setText("ID Buku");

        idbukuField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbukuFieldActionPerformed(evt);
            }
        });

        tglpinjamLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tglpinjamLabel.setText("Tanggal Pinjam");

        tglkembaliLabel.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tglkembaliLabel.setText("Tanggal Kembali");

        pinjamButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        pinjamButton.setText("Pinjam");
        pinjamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tglpinjamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tglkembaliLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idtransaksiLabel)
                        .addComponent(idbukuLabel))
                    .addComponent(usernameLabel))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pinjamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(usernameField)
                    .addComponent(idbukuField)
                    .addComponent(idtransaksiField)
                    .addComponent(tglpinjamDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglkembaliDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idtransaksiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtransaksiLabel))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idbukuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idbukuLabel))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tglpinjamLabel)
                            .addComponent(tglpinjamDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(tglkembaliDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tglkembaliLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinjamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        bukuTable.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bukuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul", "Jenis", "Tahun Terbit"
            }
        ));
        jScrollPane1.setViewportView(bukuTable);
        if (bukuTable.getColumnModel().getColumnCount() > 0) {
            bukuTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            bukuTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            bukuTable.getColumnModel().getColumn(2).setPreferredWidth(20);
            bukuTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idbukuFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbukuFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbukuFieldActionPerformed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        new Main_Menu4().setVisible(true);
        this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
    }//GEN-LAST:event_exitButtonMouseClicked

    private void pinjamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamButtonActionPerformed
        // TODO add your handling code here:
        if (idtransaksiField.getText().isEmpty() || idbukuField.getText().isEmpty() || tglpinjamDate.getDate() == null || tglkembaliDate.getDate() == null){
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
        }
        else{
            User us = new User();
            us.setUsernamebaru(usernameField.getText());
            Peminjaman pem = new Peminjaman();
            pem.setTransaksi(idtransaksiField.getText());
            Buku buk = new Buku();
            buk.setId(idbukuField.getText());
            
            us.r = us.getUserUsername();
            pem.r = pem.getPeminjamanId();
            buk.r = buk.getBukuId();
            
            try {
                if (!us.r.next()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Data User tidak ditemukan");
                    usernameField.setText(null);
                    usernameField.requestFocus(); 
                    return;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Pinjam.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                if (pem.r.next()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Terdapat Duplikat Data (id_transaksi)");
                    idtransaksiField.setText(null);
                    idtransaksiField.requestFocus();
                    return;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Pinjam.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                if (!buk.r.next()) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Data Buku tidak ditemukan");
                    idbukuField.setText(null);
                    idbukuField.requestFocus(); 
                    return;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Pinjam.class.getName()).log(Level.SEVERE, null, ex);
            }

            Date pinjam = tglpinjamDate.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDatepinjam = sdf.format(pinjam);
            Date kembali = tglkembaliDate.getDate();
            String formattedDatekembali = sdf.format(kembali);
            
            Calendar calPinjam = Calendar.getInstance();
            calPinjam.setTime(tglpinjamDate.getDate());

            Calendar calKembali = Calendar.getInstance();
            calKembali.setTime(tglkembaliDate.getDate());

            if (calKembali.before(calPinjam)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Tanggal Kembali < Tanggal Pinjam");
                tglpinjamDate.setDate(null);
                tglkembaliDate.setDate(null);
                tglpinjamDate.requestFocus();
                return;
            } 

            pem.setTransaksi(idtransaksiField.getText());
            pem.setTglpinjam(formattedDatepinjam);
            pem.setTglkembali(formattedDatekembali);
            pem.setStatus("sedang dipinjam");
            pem.setBuku(idbukuField.getText());
            pem.setUsername(usernameField.getText());
            pem.insertPeminjaman();
            javax.swing.JOptionPane.showMessageDialog(null, "Pinjam Success");

            usernameField.setText(null);
            idtransaksiField.setText(null);
            idbukuField.setText(null);
            tglpinjamDate.setDate(null);
            tglkembaliDate.setDate(null);
            usernameField.requestFocus();
        }
    }//GEN-LAST:event_pinjamButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        new Main_Menu4().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bukuTable;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField idbukuField;
    private javax.swing.JLabel idbukuLabel;
    private javax.swing.JTextField idtransaksiField;
    private javax.swing.JLabel idtransaksiLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pinjamButton;
    private com.toedter.calendar.JDateChooser tglkembaliDate;
    private javax.swing.JLabel tglkembaliLabel;
    private com.toedter.calendar.JDateChooser tglpinjamDate;
    private javax.swing.JLabel tglpinjamLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
